/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glory_game_client;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author SHANUKA
 */
public class clientInterface extends javax.swing.JFrame implements ActionListener, Runnable {
String txt;
private JButton jBut;
private Client client;
private DatagramSocket socket;
private InetAddress ip;
private int port = 8080;
private Timer countdown;
private Thread run,listen;
private boolean running = false;
private static int pos=0;
private static int jb1=0,jb2=0,jb3=0,jb4=0,jb5=0,jb6=0,jb7=0,jb8=0,jb9=0,jb10=0,jb11=0;
RandomLetterGen rg=new RandomLetterGen();


    /**
     * Creates new form clientInterface
     */
    public clientInterface() {
        initComponents();
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jButton3.addActionListener(this);
        jButton4.addActionListener(this);
        jButton5.addActionListener(this);
        jButton6.addActionListener(this);
        jButton7.addActionListener(this);
        jButton8.addActionListener(this);
        jButton9.addActionListener(this);
        jButton10.addActionListener(this);
        jButton11.addActionListener(this);
        jButton14.addActionListener(this);
        jButton16.addActionListener(this);
        jButton17.addActionListener(this);
        jButton18.addActionListener(this);
        jButton19.addActionListener(this);
        jButton20.addActionListener(this);
        jButton21.addActionListener(this);
        jButton23.addActionListener(this);
        jButton24.addActionListener(this);
        jButton25.addActionListener(this);
        jButton26.addActionListener(this);
        jButton27.addActionListener(this);
        
        jButton13.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(791, 650));
        setMinimumSize(new java.awt.Dimension(791, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(791, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("I");
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 350, 60, 40);

        jButton2.setText("E");
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 350, 60, 40);

        jButton3.setText("D");
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 350, 60, 40);

        jButton4.setText("?");
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 410, 60, 40);

        jButton5.setText("?");
        getContentPane().add(jButton5);
        jButton5.setBounds(380, 410, 60, 40);

        jButton6.setText("?");
        getContentPane().add(jButton6);
        jButton6.setBounds(450, 410, 60, 40);

        jButton7.setText("?");
        getContentPane().add(jButton7);
        jButton7.setBounds(310, 460, 60, 40);

        jButton8.setText("?");
        getContentPane().add(jButton8);
        jButton8.setBounds(380, 460, 60, 40);

        jButton9.setText("?");
        getContentPane().add(jButton9);
        jButton9.setBounds(450, 460, 60, 40);

        jButton10.setText("?");
        getContentPane().add(jButton10);
        jButton10.setBounds(340, 510, 60, 40);

        jButton11.setText("?");
        getContentPane().add(jButton11);
        jButton11.setBounds(420, 510, 60, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Letters");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 320, 80, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Vowels :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 450, 80, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Constants :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 490, 80, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("60");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 190, 70, 60);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 440, 50, 30);

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton13.setText("Submit");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(120, 580, 100, 30);

        jButton14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton14.setText("Start");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(10, 580, 100, 30);

        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton15.setText("Next Round");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(230, 580, 100, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 250, 270, 40);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Score"
            }
        ));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(540, 350, 230, 270);

        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(70, 140, 60, 40);

        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(130, 140, 60, 40);
        getContentPane().add(jButton18);
        jButton18.setBounds(190, 140, 60, 40);

        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(310, 140, 60, 40);

        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(250, 140, 60, 40);
        getContentPane().add(jButton21);
        jButton21.setBounds(370, 140, 60, 40);
        getContentPane().add(jButton23);
        jButton23.setBounds(430, 140, 60, 40);
        getContentPane().add(jButton24);
        jButton24.setBounds(490, 140, 60, 40);
        getContentPane().add(jButton25);
        jButton25.setBounds(550, 140, 60, 40);
        getContentPane().add(jButton26);
        jButton26.setBounds(610, 140, 60, 40);
        getContentPane().add(jButton27);
        jButton27.setBounds(670, 140, 60, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 490, 30, 14);

        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton12.setText("Confirm");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(120, 520, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/client.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 650);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 430, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int num=Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int rmd=8-num;
        
        jLabel6.setText(Integer.toString(rmd));
    }//GEN-LAST:event_jComboBox1ActionPerformed
public boolean x=false;
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        countdown.stop();
        String fullword=jButton16.getText()+jButton17.getText()+jButton18.getText()+jButton19.getText()+jButton20.getText()+jButton21.getText()
                +jButton23.getText()+jButton24.getText()+jButton25.getText()+jButton26.getText()+jButton27.getText();
        jTextField2.setText(fullword);
        
        String cc=jTextField2.getText();
        FindScore fs=new FindScore();
        jButton13.setEnabled(false);
        int tt=Integer.parseInt(jLabel5.getText());
        int timeu=60-tt;
       
        try{
            URL url=new URL("http://words.bighugelabs.com/api/2/7ae9f02fac417adafe6cdfc71b85f9c8/"+cc+"/");
            BufferedReader in=new BufferedReader(new InputStreamReader(url.openStream()));
            
            String str;
            String inputLine;
            while ((inputLine=in.readLine())!=null)
            {
                x=true;
            }
        }catch(Exception e){
            x=false;
            JOptionPane.showMessageDialog(null,"Invalid word");
        }
        if(x==true)
        {
            String newsco=fs.calscore(cc,timeu,jButton1.getText(),jButton2.getText(),jButton3.getText());
            byte[] Str2=newsco.getBytes();
            client.send(newsco.getBytes());
            if(newsco=="00")
            {
                JOptionPane.showMessageDialog(null, "You didn't use initial letters");
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String camount = jLabel6.getText();
        int con= Integer.parseInt(camount);
        setconsonents(con);
        
        String vamount=jComboBox1.getSelectedItem().toString();
        int vowel=Integer.parseInt(vamount);
        setvowels(vowel);
        
        jButton14.setEnabled(true);
        jButton12.setEnabled(false);
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        setinitiallet();
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(true);
        jButton11.setEnabled(true);
        
        jButton16.setText("");
        jButton17.setText("");
        jButton18.setText("");
        jButton19.setText("");
        jButton20.setText("");
        jButton21.setText("");
        jButton23.setText("");
        jButton24.setText("");
        jButton25.setText("");
        jButton26.setText("");
        jButton27.setText("");
        
        jButton12.setEnabled(true);
        
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jButton13.setEnabled(true);
        countdown=new Timer(1000,new ActionListener(){
            int count=60;
            @Override
            public void actionPerformed(ActionEvent e){
                count--;
                if(count==0) {countdown.stop();
                JOptionPane.showMessageDialog(null, "Game over");
                String gsco="00";
                client.send(gsco.getBytes());
                jButton13.setEnabled(false);
                jButton12.setEnabled(false);
                jButton14.setEnabled(false);
                jButton13.setEnabled(false);
                
                }
                jLabel5.setText(String.valueOf(count));
            }
        });
        countdown.start();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        String ename="/k/" + client.getName();
        client.send(ename.getBytes());
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing
@Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==jButton1)
        {
            jb1++;
            txt=jButton1.getText();
            pos++;
            if(jb1==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton1.setEnabled(false);
        }
        if(e.getSource()==jButton2)
        {
            jb2++;
            txt=jButton2.getText();
            pos++;
            if(jb2==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton2.setEnabled(false);
        }
        if(e.getSource()==jButton4)
        {
            jb4++;
            txt=jButton4.getText();
            pos++;
            if(jb4==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton4.setEnabled(false);
        }
        if(e.getSource()==jButton5)
        {
            jb5++;
            txt=jButton5.getText();
            pos++;
            if(jb5==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton5.setEnabled(false);
        }
        if(e.getSource()==jButton6)
        {
            jb6++;
            txt=jButton6.getText();
            pos++;
            if(jb6==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton6.setEnabled(false);
        }
        if(e.getSource()==jButton7)
        {
            jb7++;
            txt=jButton7.getText();
            pos++;
            if(jb7==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton7.setEnabled(false);
        }
        if(e.getSource()==jButton8)
        {
            jb8++;
            txt=jButton8.getText();
            pos++;
            if(jb8==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton8.setEnabled(false);
        }
        if(e.getSource()==jButton9)
        {
            jb9++;
            txt=jButton9.getText();
            pos++;
            if(jb9==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton9.setEnabled(false);
        }
        if(e.getSource()==jButton10)
        {
            jb10++;
            txt=jButton10.getText();
            pos++;
            if(jb10==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton10.setEnabled(false);
        }
        if(e.getSource()==jButton3)
        {
            jb3++;
            txt=jButton3.getText();
            pos++;
            if(jb3==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton3.setEnabled(false);
        }
        if(e.getSource()==jButton11)
        {
            jb1++;
            txt=jButton11.getText();
            pos++;
            if(jb11==1){letterbtnset(pos,txt);}
            else{enterfreespaces(txt);}
            jButton11.setEnabled(false);
        }
        if(e.getSource()==jButton16)
        {
            txt=jButton16.getText();
            wordletterset(txt);
            jButton16.setText("");
        }
        if(e.getSource()==jButton17)
        {
            txt=jButton17.getText();
            wordletterset(txt);
            jButton17.setText("");
        }
        if(e.getSource()==jButton18)
        {
            txt=jButton18.getText();
            wordletterset(txt);
            jButton18.setText("");
        }
        if(e.getSource()==jButton19)
        {
            txt=jButton19.getText();
            wordletterset(txt);
            jButton19.setText("");
        }
        if(e.getSource()==jButton20)
        {
            txt=jButton20.getText();
            wordletterset(txt);
            jButton20.setText("");
        }
        if(e.getSource()==jButton21)
        {
            txt=jButton21.getText();
            wordletterset(txt);
            jButton21.setText("");
        }
        if(e.getSource()==jButton23)
        {
            txt=jButton23.getText();
            wordletterset(txt);
            jButton23.setText("");
        }
        if(e.getSource()==jButton24)
        {
            txt=jButton24.getText();
            wordletterset(txt);
            jButton24.setText("");
        }
        if(e.getSource()==jButton25)
        {
            txt=jButton25.getText();
            wordletterset(txt);
            jButton25.setText("");
        }
        if(e.getSource()==jButton26)
        {
            txt=jButton26.getText();
            wordletterset(txt);
            jButton26.setText("");
        }
        if(e.getSource()==jButton27)
        {
            txt=jButton27.getText();
            wordletterset(txt);
            jButton27.setText("");
        }
  
    }
    public void settext(String text)
{
    String oldtxt=jTextField2.getText();
    jTextField2.setText(oldtxt + txt);
}
    public void gameStart() throws InterruptedException
    {
        timer();
    }
    static Thread td=new Thread();
    public static void timer() throws InterruptedException
    {
       for(int i=20;i>=0;i--)
       {
           td.sleep(1000);
       }
    }
    static Thread tdd=new Thread();
    public static void timer2() throws InterruptedException
    {
        for(int i=20;i>=0;i--)
        {
            tdd.sleep(1000);
            disp(i);
        }
    }
    public static void disp(int i)
    {
        jLabel7.setText(Integer.toString(i));
    }
    public void getnewtimer()
    {
        countdown=new Timer(1000,null);
    }
    public void createview(String name)
    {
        jButton14.setEnabled(false);
        jButton15.setEnabled(false);
        jTextField2.setEditable(false);
        btntransparent();
        client=new Client(name,"localhost",port);
        
        boolean connect=client.openConnection("localhost");
        if(!connect){
            System.err.println("Connection failed!");
        }
        String connection="/c/" + name;
        client.send(connection.getBytes());
        this.setVisible(true);
        setinitiallet();
        running=true;
        run=new Thread(this,"running");
        
        run.start();
    }
    public void run(){
        listen();
    }
    public void listen(){
        listen=new Thread("Listen"){
            @SuppressWarnings("empty-statement")
            public void run(){
                while(running){
                    String message=client.receive();
                    
                    if(message.startsWith("/m/")){
                        String text=message.split("m/|/e/")[1];
                    }else if(message.startsWith("/p/")){
                        JOptionPane.showMessageDialog(null, "Player amount full please try again later");
                        dispose();
                    }else if(message.startsWith("/r/")){
                        String text=message.split("r/|/e/")[1];
                        JOptionPane.showMessageDialog(null,text);
                        jButton14.setEnabled(false);
                        jButton13.setEnabled(false);
                        jButton15.setEnabled(true);
                        jTextField2.setText("");
                    }else if(message.startsWith("/h/")){
                        String text=message.split("h/|/e/")[1];
                        JOptionPane.showMessageDialog(null,message);
                        int dialogButton=JOptionPane.YES_NO_OPTION;
                        int dialogResult=JOptionPane.showConfirmDialog(null, "Would You Like to Remove a Player?","Warning",dialogButton);
                        if(dialogResult==JOptionPane.YES_OPTION){
                            String test1=JOptionPane.showInputDialog("Please enter player name that you want to punish : ");
                            String ename="/z/" + test1;
                            client.send(ename.getBytes());
                        }
                    }else if(message.startsWith("/y/")){
                        JOptionPane.showMessageDialog(null, "You have been eliminated by top scorer");
                        System.exit(0);
                    }else if(message.startsWith("/a/")){
                        String text=message.split("a/|/e/")[1];
                        Object[] row={text};
                        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
                        model.addRow(row);
                    }else if(message.startsWith("/w/")){
                        String text=message.split("w/|/e/")[1];
                        JOptionPane.showMessageDialog(null, text);
                        
                        int dialogButton=JOptionPane.YES_NO_OPTION;
                        int dialogResult=JOptionPane.showConfirmDialog(null, "Would You Like to Play again?","Warning",dialogButton);
                        if(dialogResult==JOptionPane.YES_OPTION){
                            String test1="exit";
                            JOptionPane.showMessageDialog(rootPane, "Please re-run server");
                            String exi="/v/" + test1;
                            client.send(exi.getBytes());
                            System.exit(0);
                        }else if(dialogResult==JOptionPane.NO_OPTION){
                            String test1="exit";
                            String exi="/v/" + test1;
                            client.send(exi.getBytes());
                        }
                    }else
                    {
                        jButton13.setEnabled(false);
                        String text=message.split("/c/|/e/")[1];
                        JOptionPane.showMessageDialog(null,"Your game ID : " + text);
                    }
                }
            }
        };
        listen.start();
    }
public void setinitiallet()
{
    String word=rg.generateRandomString();
    for(int i=0;i<3;i++)
    {
        char ch = word.charAt(i);
        String x=Character.toString(ch);
        if(i==0)
            jButton1.setText(x);
        else if(i==1)
            jButton2.setText(x);
        else if(i==2)
            jButton3.setText(x);
        
    }
}
public void setconsonents(int amount)
{
    int conamount = amount;
    String word= rg.generateRandomStringCon(conamount);
    
    if(conamount==5){
        for(int i=0;i<5;i++)
        {
            char ch=word.charAt(i);
            String x=Character.toString(ch);
            if(i==0)jButton4.setText(x);
            else if(i==1)jButton5.setText(x);
            else if(i==2)jButton6.setText(x);
            else if(i==3)jButton7.setText(x);
            else if(i==4)jButton8.setText(x);
        }}
    else if(conamount==6)
            {
            for(int i=0;i<6;i++)
            { char ch=word.charAt(i);
            String x=Character.toString(ch);
            if(i==0)jButton4.setText(x);
            else if(i==1)jButton5.setText(x);
            else if(i==2)jButton6.setText(x);
            else if(i==3)jButton7.setText(x);
            else if(i==4)jButton8.setText(x);
            else if(i==5)jButton9.setText(x);
            }}
    else if(conamount==7){
        for(int i=0;i<7;i++)
        { char ch=word.charAt(i);
        String x=Character.toString(ch);
        if(i==0)jButton4.setText(x);
        else if(i==1)jButton5.setText(x);
        else if(i==2)jButton6.setText(x);
        else if(i==3)jButton7.setText(x);
        else if(i==4)jButton8.setText(x);
        else if(i==5)jButton9.setText(x);
        else if(i==6)jButton10.setText(x);
            }
            }
    else if(conamount==8){
        for(int i=0;i<8;i++)
        { char ch=word.charAt(i);
        String x=Character.toString(ch);
        if(i==0)jButton3.setText(x);
        else if(i==1)jButton4.setText(x);
        else if(i==2)jButton5.setText(x);
        else if(i==3)jButton6.setText(x);
        else if(i==4)jButton7.setText(x);
        else if(i==5)jButton8.setText(x);
        else if(i==6)jButton9.setText(x);
        else if(i==7)jButton10.setText(x);
        }
    }
}
    public void setvowels(int amount)
    {
        int conamount=amount;
        String word=rg.generateRandomStringVowel(conamount);
        if(conamount==3){
            for(int i=0;i<3;i++)
            { char ch=word.charAt(i);
            String x=Character.toString(ch);
            if(i==0)jButton9.setText(x);
            else if(i==1)jButton10.setText(x);
            else if(i==2)jButton11.setText(x);
            }
        }
        else if(conamount==2){
            for(int i=0;i<2;i++)
            { char ch = word.charAt(i);
            String x=Character.toString(ch);
            if(i==0)jButton10.setText(x);
            else if(i==1)jButton11.setText(x);
            }
        }
        else if(conamount==1){
            for(int i=0;i<1;i++)
            { char ch= word.charAt(i);
            String x=Character.toString(ch);
            if(i==0)jButton11.setText(x);
            }
        }
    }
        public void letterbtnset(int posval, String letval)
        {
            int poss=posval;
            String let=letval;
            if(poss==1){ jButton16.setText(let);}
            if(poss==2){ jButton17.setText(let);}
            if(poss==3){ jButton18.setText(let);}
            if(poss==4){ jButton19.setText(let);}
            if(poss==5){ jButton20.setText(let);}
            if(poss==6){ jButton21.setText(let);}
            if(poss==7){ jButton23.setText(let);}
            if(poss==8){ jButton24.setText(let);}
            if(poss==9){ jButton25.setText(let);}
            if(poss==10){ jButton26.setText(let);}
            if(poss==11){ jButton27.setText(let);}
        }
        public void wordletterset(String wordletval)
        {
         String wordlet=wordletval;   
         if(wordlet==jButton1.getText()){jButton1.setEnabled(true);}
         if(wordlet==jButton2.getText()){jButton2.setEnabled(true);}
         if(wordlet==jButton3.getText()){jButton3.setEnabled(true);}
         if(wordlet==jButton4.getText()){jButton4.setEnabled(true);}
         if(wordlet==jButton5.getText()){jButton5.setEnabled(true);}
         if(wordlet==jButton6.getText()){jButton6.setEnabled(true);}
         if(wordlet==jButton7.getText()){jButton7.setEnabled(true);}
         if(wordlet==jButton8.getText()){jButton8.setEnabled(true);}
         if(wordlet==jButton9.getText()){jButton9.setEnabled(true);}
         if(wordlet==jButton10.getText()){jButton10.setEnabled(true);}
         if(wordlet==jButton11.getText()){jButton11.setEnabled(true);}
            
        }
        public void enterfreespaces(String freeletval)
        {
            String freelet=freeletval;
            if(jButton16.getText()==""){jButton16.setText(freelet);}
            if(jButton17.getText()==""){jButton17.setText(freelet);}
            if(jButton18.getText()==""){jButton18.setText(freelet);}
            if(jButton19.getText()==""){jButton19.setText(freelet);}
            if(jButton20.getText()==""){jButton20.setText(freelet);}
            if(jButton21.getText()==""){jButton21.setText(freelet);}
            if(jButton23.getText()==""){jButton23.setText(freelet);}
            if(jButton24.getText()==""){jButton24.setText(freelet);}
            if(jButton25.getText()==""){jButton25.setText(freelet);}
            if(jButton26.getText()==""){jButton26.setText(freelet);}
            if(jButton27.getText()==""){jButton27.setText(freelet);}
        }
        public void btntransparent()
        {
          jButton1.setContentAreaFilled(false);
          jButton2.setContentAreaFilled(false);
          jButton3.setContentAreaFilled(false);
          jButton4.setContentAreaFilled(false);
          jButton5.setContentAreaFilled(false);
          jButton6.setContentAreaFilled(false);
          jButton7.setContentAreaFilled(false);
          jButton8.setContentAreaFilled(false);
          jButton9.setContentAreaFilled(false);
          jButton10.setContentAreaFilled(false);
          jButton11.setContentAreaFilled(false);
          jButton16.setContentAreaFilled(false);
          jButton17.setContentAreaFilled(false);
          jButton18.setContentAreaFilled(false);
          jButton19.setContentAreaFilled(false);
          jButton20.setContentAreaFilled(false);
          jButton21.setContentAreaFilled(false);
          jButton23.setContentAreaFilled(false);
          jButton24.setContentAreaFilled(false);
          jButton25.setContentAreaFilled(false);
          jButton26.setContentAreaFilled(false);
          jButton27.setContentAreaFilled(false);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    
}
